extends Node
@export var mob_scene: PackedScene
@export var item_scene: PackedScene
var score
var score_mult = 1
signal game_state_changed
var game_active: bool = false

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass


func game_over() -> void:
	$ScoreTimer.stop()
	$MobTimer.stop()
	$PowerUpSpawnTimer.stop()
	$Music.stop()
	$DeathSound.play()
	$HUD.show_game_over()
	game_state_changed.emit()
	game_active = not game_active


func new_game():
	get_tree().call_group("mobs", "queue_free")
	get_tree().call_group("power_ups", "queue_free")
	score = 0
	$Music.play()
	$Player.start($StartPosition.position)
	$StartTimer.start()
	$HUD.update_score(score)
	game_state_changed.emit()
	game_active = not game_active
	$HUD.show_message("Get Ready")


func _on_mob_timer_timeout() -> void:
	# Create a new instance of the Mob scene.
	var mob = mob_scene.instantiate()

	# Choose a random location on Path2D.
	var mob_spawn_location = $MobPath/MobSpawnLocation
	mob_spawn_location.progress_ratio = randf()

	# Set the mob's position to the random location.
	mob.position = mob_spawn_location.position

	# Set the mob's direction perpendicular to the path direction.
	var direction = mob_spawn_location.rotation + PI / 2

	# Add some randomness to the direction.
	direction += randf_range(-PI / 4, PI / 4)
	mob.rotation = direction

	# Choose the velocity for the mob.
	var velocity = Vector2(randf_range(150.0, 250.0), 0.0)
	mob.linear_velocity = velocity.rotated(direction)

	# Spawn the mob by adding it to the Main scene.
	add_child(mob)


func _on_score_timer_timeout() -> void:
	score += 1 * score_mult
	$HUD.update_score(score)


func _on_start_timer_timeout() -> void:
	$MobTimer.start()
	$ScoreTimer.start()
	$PowerUpSpawnTimer.start()




func _on_power_up_timer_timeout() -> void:
	score_mult = 1


func _on_power_up_spawn_timer_timeout() -> void:
	var item = item_scene.instantiate()
	
	add_child(item)
	
	# pick a random position inside the viewport (generated by ai)
	var rect: Rect2 = get_viewport().get_visible_rect()
	var x = randf_range(0, rect.size.x)
	var y = randf_range(0, rect.size.y)
	item.global_position = Vector2(x, y)
	# end ai


func _on_player_hit_power_up() -> void:
	print("pickedup")
	score_mult = 2
	$PowerUpTimer.start()
	$PowerUp.queue_free()
